name = "my-blog"
compatibility_date = "2025-02-04"

[env.production]
kv_namespaces = [
  { binding = "BLOG_DB", id = "7813d5f465764dc09a283a50337bf7a1" }
]

[env.preview]
kv_namespaces = [
  { binding = "BLOG_DB", id = "YOUR_PREVIEW_KV_ID" }
]